// ============================================================================
// MeedyaConverter — AudioFingerprinter
// Copyright © 2026 MWBM Partners Ltd. All rights reserved.
// Proprietary and confidential. Unauthorized copying or distribution
// of this file, via any medium, is strictly prohibited.
// ============================================================================

import Foundation

// MARK: - AudioFingerprint

/// An audio fingerprint generated by Chromaprint.
public struct AudioFingerprint: Codable, Sendable {
    /// The raw fingerprint data (compressed integer array).
    public var fingerprint: String

    /// Duration of the audio that was fingerprinted (in seconds).
    public var duration: TimeInterval

    /// The audio stream index that was fingerprinted.
    public var streamIndex: Int?

    /// The source file path.
    public var sourcePath: String

    public init(
        fingerprint: String,
        duration: TimeInterval,
        streamIndex: Int? = nil,
        sourcePath: String
    ) {
        self.fingerprint = fingerprint
        self.duration = duration
        self.streamIndex = streamIndex
        self.sourcePath = sourcePath
    }
}

// MARK: - FingerprintMatch

/// A match result from AcoustID lookup.
public struct FingerprintMatch: Codable, Sendable {
    /// Match confidence score (0.0–1.0).
    public var confidence: Double

    /// AcoustID identifier.
    public var acoustId: String?

    /// MusicBrainz recording ID.
    public var recordingId: String?

    /// Track title (if available).
    public var title: String?

    /// Artist name (if available).
    public var artist: String?

    /// Album title (if available).
    public var album: String?

    public init(
        confidence: Double,
        acoustId: String? = nil,
        recordingId: String? = nil,
        title: String? = nil,
        artist: String? = nil,
        album: String? = nil
    ) {
        self.confidence = confidence
        self.acoustId = acoustId
        self.recordingId = recordingId
        self.title = title
        self.artist = artist
        self.album = album
    }

    /// Whether this is a high-confidence match.
    public var isHighConfidence: Bool {
        confidence >= 0.8
    }
}

// MARK: - FingerprintComparison

/// Result of comparing two audio fingerprints locally.
public struct FingerprintComparison: Sendable {
    /// Similarity score (0.0–1.0). Higher = more similar.
    public var similarity: Double

    /// Whether the files are likely the same audio content.
    public var isLikelyMatch: Bool {
        similarity >= 0.7
    }

    /// Whether the files are definitely the same content.
    public var isDefiniteMatch: Bool {
        similarity >= 0.9
    }

    public init(similarity: Double) {
        self.similarity = similarity
    }
}

// MARK: - AudioFingerprinter

/// Generates audio fingerprints using FFmpeg's Chromaprint integration
/// and provides tools for identification and comparison.
///
/// Chromaprint generates compact acoustic fingerprints that can identify
/// audio content regardless of encoding format, bitrate, or quality.
///
/// Phase 7.18
public struct AudioFingerprinter: Sendable {

    /// Build FFmpeg arguments to generate a Chromaprint fingerprint.
    ///
    /// - Parameters:
    ///   - inputPath: Path to the audio/video file.
    ///   - duration: Maximum duration to fingerprint (in seconds). Nil = full track.
    ///   - streamIndex: Specific audio stream to fingerprint. Nil = default stream.
    /// - Returns: FFmpeg argument array.
    public static func buildFingerprintArguments(
        inputPath: String,
        duration: TimeInterval? = nil,
        streamIndex: Int? = nil
    ) -> [String] {
        var args: [String] = []

        if let dur = duration {
            args += ["-t", String(format: "%.1f", dur)]
        }

        args += ["-i", inputPath]

        if let idx = streamIndex {
            args += ["-map", "0:a:\(idx)"]
        }

        // Chromaprint output
        args += ["-f", "chromaprint"]
        args += ["-fp_format", "compressed"]
        args += ["-"]

        return args
    }

    /// Build FFmpeg arguments for raw fingerprint generation (for local comparison).
    ///
    /// - Parameters:
    ///   - inputPath: Path to the audio/video file.
    ///   - duration: Maximum duration to fingerprint.
    /// - Returns: FFmpeg argument array.
    public static func buildRawFingerprintArguments(
        inputPath: String,
        duration: TimeInterval? = nil
    ) -> [String] {
        var args: [String] = []

        if let dur = duration {
            args += ["-t", String(format: "%.1f", dur)]
        }

        args += ["-i", inputPath]
        args += ["-f", "chromaprint"]
        args += ["-fp_format", "raw"]
        args += ["-"]

        return args
    }

    /// Build the AcoustID API lookup URL.
    ///
    /// - Parameters:
    ///   - fingerprint: The Chromaprint fingerprint string.
    ///   - duration: Audio duration in seconds.
    ///   - apiKey: AcoustID API key.
    /// - Returns: The API lookup URL string.
    public static func buildAcoustIDLookupURL(
        fingerprint: String,
        duration: Int,
        apiKey: String
    ) -> String {
        let base = "https://api.acoustid.org/v2/lookup"
        return "\(base)?client=\(apiKey)&duration=\(duration)&fingerprint=\(fingerprint)&meta=recordings+releasegroups+compress"
    }

    /// Parse Chromaprint output from FFmpeg.
    ///
    /// FFmpeg outputs the fingerprint as a single line of text when using
    /// the chromaprint format.
    ///
    /// - Parameter output: FFmpeg stdout output.
    /// - Returns: The fingerprint string, or nil if parsing fails.
    public static func parseFingerprint(from output: String) -> String? {
        // The chromaprint output is typically on the last non-empty line
        let lines = output.split(separator: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .filter { !$0.isEmpty }

        // Find the fingerprint line (it's a long base64-like string)
        for line in lines.reversed() {
            if line.count > 20 && !line.contains("=") && !line.contains(":") {
                return line
            }
            // Also check for FINGERPRINT= format
            if line.hasPrefix("FINGERPRINT=") {
                return String(line.dropFirst("FINGERPRINT=".count))
            }
        }

        return lines.last
    }

    /// Compute similarity between two raw fingerprint arrays.
    ///
    /// Uses bit-level Hamming distance to compare fingerprints.
    ///
    /// - Parameters:
    ///   - fp1: First fingerprint as array of UInt32 values.
    ///   - fp2: Second fingerprint as array of UInt32 values.
    /// - Returns: Similarity score (0.0–1.0).
    public static func compareFingerprints(
        _ fp1: [UInt32],
        _ fp2: [UInt32]
    ) -> FingerprintComparison {
        let length = min(fp1.count, fp2.count)
        guard length > 0 else {
            return FingerprintComparison(similarity: 0)
        }

        var matchingBits = 0
        let totalBits = length * 32

        for i in 0..<length {
            let xor = fp1[i] ^ fp2[i]
            // Count matching bits (invert popcount)
            matchingBits += 32 - xor.nonzeroBitCount
        }

        let similarity = Double(matchingBits) / Double(totalBits)
        return FingerprintComparison(similarity: similarity)
    }
}
